"""Fraud AI (spec Part 14) - a REAL trained classifier, distinct from
ANOMALY_AI's unsupervised statistics.

Trained on pointe77/credit-card-transaction (Apache-2.0, Hugging Face) -
synthetic transaction data generated by the well-known Sparkov simulator
for fraud-detection research/education, not real cardholders. Streamed
via the same bounded-token/record HF loader pattern already used
throughout this project; never materializes the full dataset.

A logistic regression with class_weight='balanced' (not a deep model -
no GPU needed, and honest about what it is) on transaction amount, time
features, and category. Reports real precision/recall/F1 on a held-out
split - accuracy alone is meaningless at a ~0.75% fraud rate.
"""

import datetime
import json
import os
import pickle

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    confusion_matrix, f1_score, precision_score, recall_score, roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

MODEL_DIR = os.path.join("checkpoints", "fraud")
MODEL_PATH = os.path.join(MODEL_DIR, "fraud_model.pkl")
META_PATH = os.path.join(MODEL_DIR, "fraud_model.json")

DATASET_ID = "pointe77/credit-card-transaction"
FEATURE_CATEGORIES = None  # fitted at train time, stored in the pickle


def _featurize(records):
    """Turn raw HF records into a numeric feature matrix. Real, simple,
    inspectable features - no LLM embeddings involved."""
    amounts, hours, dows, city_pops, categories, labels = [], [], [], [], [], []
    for r in records:
        try:
            dt = datetime.datetime.strptime(r["trans_date_trans_time"], "%Y-%m-%d %H:%M:%S")
        except (ValueError, TypeError):
            continue
        amounts.append(float(r["amt"]))
        hours.append(dt.hour)
        dows.append(dt.weekday())
        city_pops.append(float(r.get("city_pop", 0) or 0))
        categories.append(str(r.get("category", "unknown")))
        labels.append(int(r["is_fraud"]))
    return {
        "amount": np.array(amounts), "hour": np.array(hours), "dow": np.array(dows),
        "city_pop": np.array(city_pops), "category": np.array(categories),
        "label": np.array(labels),
    }


def _build_matrix(features, encoder=None, fit=False):
    cat = features["category"].reshape(-1, 1)
    if fit:
        encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
        cat_encoded = encoder.fit_transform(cat)
    else:
        cat_encoded = encoder.transform(cat)

    numeric = np.column_stack([
        features["amount"], np.log1p(features["amount"]),
        features["hour"], features["dow"], np.log1p(features["city_pop"]),
    ])
    X = np.hstack([numeric, cat_encoded])
    return X, encoder


def stream_training_records(max_records: int = 60_000):
    """Stream records from the HF dataset, bounded - never the full set."""
    from datasets import load_dataset
    ds = load_dataset(DATASET_ID, split="train", streaming=True)
    records = []
    for i, ex in enumerate(ds):
        if i >= max_records:
            break
        records.append(ex)
    return records


def train(max_records: int = 60_000, seed: int = 42, test_size: float = 0.25):
    records = stream_training_records(max_records)
    features = _featurize(records)

    X_all, encoder = _build_matrix(features, fit=True)
    y_all = features["label"]

    X_train, X_test, y_train, y_test = train_test_split(
        X_all, y_all, test_size=test_size, random_state=seed, stratify=y_all,
    )

    model = RandomForestClassifier(
        n_estimators=100, max_depth=10, class_weight="balanced",
        random_state=seed, n_jobs=-1,
    )
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    metrics = {
        "precision": round(float(precision_score(y_test, y_pred, zero_division=0)), 4),
        "recall": round(float(recall_score(y_test, y_pred, zero_division=0)), 4),
        "f1": round(float(f1_score(y_test, y_pred, zero_division=0)), 4),
        "roc_auc": round(float(roc_auc_score(y_test, y_proba)), 4),
        "confusion_matrix": confusion_matrix(y_test, y_pred).tolist(),  # [[TN,FP],[FN,TP]]
        "test_size": int(len(y_test)),
        "test_fraud_count": int(y_test.sum()),
        "train_size": int(len(y_train)),
        "train_fraud_count": int(y_train.sum()),
    }

    os.makedirs(MODEL_DIR, exist_ok=True)
    with open(MODEL_PATH, "wb") as f:
        pickle.dump({"model": model, "encoder": encoder}, f)

    meta = {
        "dataset_id": DATASET_ID, "dataset_license": "apache-2.0",
        "dataset_note": "Synthetic data (Sparkov simulator), not real cardholders.",
        "records_used": len(records), "seed": seed, "test_size": test_size,
        "algorithm": "sklearn.ensemble.RandomForestClassifier(n_estimators=100, max_depth=10, class_weight='balanced')",
        "features": ["amount", "log1p(amount)", "hour", "day_of_week", "log1p(city_pop)", "category (one-hot)"],
        "metrics": metrics,
        "trained_at": datetime.datetime.utcnow().isoformat() + "Z",
    }
    with open(META_PATH, "w") as f:
        json.dump(meta, f, indent=2)

    return meta


class FraudModel:
    def __init__(self):
        if not os.path.exists(MODEL_PATH):
            raise FileNotFoundError(
                f"No trained fraud model at {MODEL_PATH}. Run ai_platform.fraud.train() first."
            )
        with open(MODEL_PATH, "rb") as f:
            saved = pickle.load(f)
        self.model = saved["model"]
        self.encoder = saved["encoder"]
        with open(META_PATH) as f:
            self.meta = json.load(f)

    def score(self, transactions: list) -> list:
        """transactions: list of {amt, category, trans_date_trans_time, city_pop}.
        Returns a risk score in [0, 1] per transaction from the trained model -
        not a fabricated number."""
        features = _featurize([
            {**t, "is_fraud": 0} for t in transactions  # label unused at inference
        ])
        if len(features["amount"]) == 0:
            return []
        X, _ = _build_matrix(features, encoder=self.encoder, fit=False)
        proba = self.model.predict_proba(X)[:, 1]
        return [round(float(p), 4) for p in proba]


def load_model() -> FraudModel:
    return FraudModel()
