"""A calculation split built from captions the operand vocabulary does NOT have.

The first fresh split answered "did the vocabulary overfit to the eight frozen
items it was written from?" - it did not, 44/44. It could not answer "does the
vocabulary generalise to captions nobody wrote into it", because all 44 of its
captions happened to be covered.

This answers that. Every caption here is checked programmatically against
`SYNONYMS` and kept ONLY if no operand field resolves it. Candidates that turn
out to be covered are discarded and counted, so the split cannot quietly drift
back into the covered set.

## Pre-registered prediction, written before the run

Traced through the code first, because the obvious prediction was wrong. When
`resolve_field` finds no caption it returns None, and `_calculate` then asks the
model for the **canonical** operand name anyway - "Find the value for: revenue"
against a context whose only revenue line says "Gross billings".

So this does not test whether the pipeline refuses. It tests **whether the model
bridges the synonym gap the vocabulary does not cover**, with the span rule
still enforced on whatever it returns.

Three outcomes, and they mean different things:

  * **High accuracy** - the model resolves these captions unaided, which means
    the 147-caption table is doing less work than its size suggests and the
    leakage concern largely dissolves.
  * **High abstention, no wrong values** - the safe failure. The vocabulary is
    load-bearing, and uncovered captions degrade to refusal rather than error.
  * **Wrong values returned** - the outcome that matters. It would mean the
    model picks a plausible wrong line and the span rule passes it, because a
    span can be valid while the line is the wrong one. Task 3 already found two
    such cases on the frozen set, goodwill and cash generated from operations.

No prediction is registered on which of the first two wins; the mechanism is
genuinely uncertain. The third is the one to watch, and the first fresh split
cannot produce it because its captions all resolved in code.

    python scripts/build_uncovered_caption_split.py
"""

import json
import os
import random
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from pipeline.tool_pipeline import SYNONYMS, ToolPipeline  # noqa: E402

OUT_DIR = os.path.join("data", "eval_fresh")
OUT = os.path.join(OUT_DIR, "calculation_uncovered.jsonl")
SEED = 20261007

# Real statement wordings from sectors the project has not touched - insurance,
# shipping, banking, mutuals, partnerships. Each is a plausible caption for the
# role given; whether the vocabulary knows it is tested below, not assumed.
CANDIDATES = {
    "revenue": ["Gross billings", "Fee and commission income", "Premiums earned",
                "Charter hire income", "Subscription income", "Gross written premium",
                "Rental income receivable", "Takings for the period"],
    "cost of sales": ["Direct operating costs", "Cost of services rendered",
                      "Claims incurred", "Vessel running costs",
                      "Merchandise costs", "Cost of hire"],
    "net income": ["Surplus for the year", "Result for the financial period",
                   "Profit after taxation and minority interests",
                   "Retained surplus"],
    "operating profit": ["Underwriting result", "Trading surplus",
                         "Segment result before central costs"],
    "current assets": ["Realisable assets", "Assets held for settlement",
                       "Short-term resources"],
    "current liabilities": ["Short-term obligations",
                            "Payables settling within twelve months",
                            "Claims outstanding"],
    "total assets": ["Balance sheet total", "Total resources of the fund"],
    "total debt": ["Interest-bearing debt", "Senior notes and term loans",
                   "Financial liabilities at amortised cost"],
    "shareholders' equity": ["Net worth", "Members' funds", "Partners' capital",
                             "Policyholders' funds"],
    "interest expense": ["Borrowing costs", "Interest on senior notes"],
    "operating cash flow": ["Cash generated by operations",
                            "Funds from operations"],
    "capital expenditure": ["Additions to non-current assets",
                            "Investment in plant and machinery"],
    "inventory": ["Merchandise on hand", "Raw materials and finished goods"],
    "shares outstanding": ["Weighted average ordinary shares in issue"],
}

# (question, [(role, caption-key)], compute, unit, plausible ratio for operand 2)
SHAPES = [
    ("What is the gross margin?", ["revenue", "cost of sales"],
     lambda a, b: 100.0 * (a - b) / a, "%", (0.45, 0.80)),
    ("What is gross profit?", ["revenue", "cost of sales"],
     lambda a, b: a - b, "", (0.45, 0.80)),
    ("What is the net profit margin?", ["net income", "revenue"],
     lambda a, b: 100.0 * a / b, "%", (4.0, 25.0)),
    ("What is the operating margin?", ["operating profit", "revenue"],
     lambda a, b: 100.0 * a / b, "%", (4.0, 20.0)),
    ("What is the current ratio?", ["current assets", "current liabilities"],
     lambda a, b: a / b, "x", (0.35, 0.85)),
    ("What is working capital?", ["current assets", "current liabilities"],
     lambda a, b: a - b, "", (0.35, 0.85)),
    ("What is the debt-to-equity ratio?", ["total debt", "shareholders' equity"],
     lambda a, b: a / b, "x", (1.2, 4.0)),
    ("What is return on assets as a percentage?", ["net income", "total assets"],
     lambda a, b: 100.0 * a / b, "%", (6.0, 30.0)),
    ("What is the interest cover?", ["operating profit", "interest expense"],
     lambda a, b: a / b, "x", (0.05, 0.30)),
    ("What is free cash flow?", ["operating cash flow", "capital expenditure"],
     lambda a, b: a - b, "", (0.25, 0.70)),
    ("What is earnings per share?", ["net income", "shares outstanding"],
     lambda a, b: a / b, "", (60.0, 400.0)),
]

DISTRACTORS = ["Headcount at period end", "Branches in operation",
               "Average policy term", "Days sales outstanding",
               "Number of vessels", "Members admitted in the year"]


def is_uncovered(caption):
    """True only if NO operand field resolves this caption."""
    probe = f"{caption}: 1.00"
    return not any(ToolPipeline.resolve_field(probe, field) for field in SYNONYMS)


def build():
    rng = random.Random(SEED)

    uncovered, discarded = {}, []
    for role, captions in CANDIDATES.items():
        kept = [c for c in captions if is_uncovered(c)]
        discarded += [(role, c) for c in captions if c not in kept]
        if kept:
            uncovered[role] = kept

    print(f"candidate captions      {sum(len(v) for v in CANDIDATES.values())}")
    print(f"  genuinely uncovered   {sum(len(v) for v in uncovered.values())}")
    print(f"  discarded as covered  {len(discarded)}")
    for role, caption in discarded:
        print(f"      covered already: {caption!r} ({role})")

    usable = [s for s in SHAPES if all(r in uncovered for r in s[1])]
    print(f"\nquestion shapes usable  {len(usable)} of {len(SHAPES)}")
    if not usable:
        raise SystemExit("no shape has all operands uncovered")

    rows = []
    index = 0
    while len(rows) < 44:
        question, roles, compute, unit, span = usable[index % len(usable)]
        index += 1
        first = round(rng.uniform(800, 90000), 2)
        values, lines = [], []
        for position, role in enumerate(roles):
            caption = rng.choice(uncovered[role])
            value = first if position == 0 else round(first * rng.uniform(*span), 2)
            values.append(value)
            lines.append((caption, value))
        captions = [c for c, _ in lines]
        for _ in range(rng.randint(1, 2)):
            lines.append((rng.choice(DISTRACTORS), round(rng.uniform(1, 900), 2)))
        rng.shuffle(lines)

        expected = compute(*values)
        rows.append({
            "id": f"uncovered_calc_{len(rows):03d}",
            "gate": "calculation",
            "origin": "generated_uncovered_captions",
            "question": question,
            "context": "\n".join(f"{c}: {v:,.2f}" for c, v in lines),
            "expected": round(expected, 2),
            "expected_display": (f"{expected:.2f}%" if unit == "%" else
                                 f"{expected:.2f}x" if unit == "x"
                                 else f"{expected:,.2f}"),
            "operand_captions": captions,
            "note": "every operand caption verified absent from SYNONYMS",
        })

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row) + "\n")

    # Verify the written file, rather than trusting the loop that wrote it.
    still_covered = [c for row in rows for c in row["operand_captions"]
                     if not is_uncovered(c)]
    print(f"\nwrote {OUT}: {len(rows)} items")
    print(f"  distinct captions used     {len({c for r in rows for c in r['operand_captions']})}")
    print(f"  captions re-checked covered {len(still_covered)}  "
          f"(must be 0)")
    assert not still_covered, f"covered captions leaked in: {set(still_covered)}"

    with open(os.path.join(OUT_DIR, "manifest_uncovered.json"), "w",
              encoding="utf-8") as handle:
        json.dump({"items": len(rows), "seed": SEED,
                   "every_caption_verified_absent_from_vocabulary": True,
                   "discarded_as_already_covered": [c for _, c in discarded],
                   "prediction": ("resolution fails, so the model is asked for "
                                  "the canonical operand name against an "
                                  "unfamiliar caption; this measures whether the "
                                  "MODEL bridges the gap, not whether the "
                                  "pipeline refuses. No prediction registered "
                                  "between high accuracy and high abstention."),
                   "what_would_be_alarming": ("wrong numbers returned instead "
                                              "of refusals")}, handle, indent=2)
    return rows


if __name__ == "__main__":
    build()
