"""Package a trained checkpoint for a free Hugging Face model repo + Space.

The training checkpoints are ~1.2 GB because they carry Adam optimizer state,
which nobody needs in order to run the model. This writes a deployable bundle
instead:

    hf_export/
      model.safetensors        fp16 weights only (~274 MB, no pickle)
      config.json              the architecture this checkpoint was trained with
      models/                  the model code (~600 lines, torch only)
      financial_calculator.py  exact arithmetic - the model must not do sums
      financial_router.py      decides: calculator vs model
      app.py                   Gradio demo for a free CPU Space
      requirements.txt
      README.md                model card with the real, measured numbers

usage:
    python scripts/export_for_huggingface.py \
        --checkpoint checkpoints/continuation_upload_latest/checkpoint_237362.pt \
        --out hf_export
"""

import argparse
import json
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

APP_PY = '''"""Aivora Financial LLM - demo Space.

The language model is 101M parameters trained from scratch on ~1.9B tokens.
It is a research/learning artifact: it writes fluent finance-flavoured text
but its facts are often wrong. Arithmetic is therefore NOT done by the model -
questions with numbers are routed to a deterministic calculator.
"""
import json
import os

import gradio as gr
import tiktoken
import torch
from safetensors.torch import load_file

from financial_calculator import CALCULATIONS, CalculationError, calculate
from derived_calculations import solve as solve_derived
from financial_router import Route, classify, extract_financial_values
from glossary import FINANCIAL_KNOWLEDGE_BASE
from models import DeepSeekConfig, DeepSeekV3
from quality import analyze_output

HERE = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(HERE, "config.json")) as f:
    META = json.load(f)

config = DeepSeekConfig.from_dict(META["model_config"])
model = DeepSeekV3(config)
state = load_file(os.path.join(HERE, "model.safetensors"))
model.load_state_dict({k: v.float() for k, v in state.items()})
model.eval()
enc = tiktoken.get_encoding("gpt2")

DISCLAIMER = ("\\n\\n_Educational output from a 101M research model - not financial "
              "advice, and its facts are often wrong._")

# Which calculation to run when the question supplies the inputs for it.
CALC_INTENTS = [
    ("ebitda_margin", ("ebitda", "revenue")),
    ("gross_margin", ("gross_profit", "revenue")),
    ("net_profit_margin", ("net_income", "revenue")),
    ("operating_margin", ("operating_income", "revenue")),
    ("current_ratio", ("current_assets", "current_liabilities")),
    ("debt_to_equity", ("debt", "equity")),
    ("roe", ("net_income", "equity")),
    ("roa", ("net_income", "total_assets")),
    ("pe_ratio", ("price_per_share", "earnings_per_share")),
    ("ev_to_ebitda", ("enterprise_value", "ebitda")),
    ("roic", ("nopat", "invested_capital")),
    ("free_cash_flow", ("operating_cash_flow", "capex")),
    ("simple_profit", ("revenue", "expenses")),
]

ARG_ALIASES = {"equity": "shareholders_equity", "debt": "total_debt",
               "capex": "capital_expenditure", "shares": "shares_outstanding"}


def try_calculator(question):
    values = extract_financial_values(question)
    # Multi-step first: questions that give the COMPONENTS (assets and
    # liabilities instead of equity, net income and shares instead of EPS)
    # would otherwise be answered with the wrong single formula.
    derived = solve_derived(question, values)
    if derived:
        inputs = ", ".join(f"{k} = {v:,.2f}" for k, v in derived.inputs.items() if v is not None)
        working = "".join(f"\\n\\n{step}" for step in derived.steps)
        return (f"**{derived.name}: {derived.formatted()}**\\n\\n"
                f"Formula: {derived.formula}\\n\\nInputs: {inputs}{working}\\n\\n"
                f"_Computed exactly by the calculator, not generated by the model._")
    for name, required in CALC_INTENTS:
        if all(r in values for r in required):
            import inspect

            fn = CALCULATIONS[name]
            kwargs = {}
            for param in inspect.signature(fn).parameters:
                for key, val in values.items():
                    if ARG_ALIASES.get(key, key) == param or key == param:
                        kwargs[param] = val
            try:
                result = calculate(name, **kwargs)
            except CalculationError as e:
                return f"Could not calculate: {e}"
            inputs = ", ".join(f"{k} = {v:,.2f}" for k, v in result.inputs.items()
                               if v is not None)
            return (f"**{result.name}: {result.formatted()}**\\n\\n"
                    f"Formula: {result.formula}\\n\\nInputs: {inputs}\\n\\n"
                    f"_Computed exactly by the calculator, not generated by the model._")
    return None


@torch.no_grad()
def generate(prompt, max_new_tokens, temperature):
    ids = enc.encode_ordinary(prompt)[-(config.block_size - max_new_tokens):]
    context = torch.tensor(ids, dtype=torch.long).unsqueeze(0)
    out = model.generate(context, max_new_tokens, temperature=temperature, top_k=40)
    return enc.decode(out[0, len(ids):].tolist()).strip()


def try_glossary(question):
    """Curated definitions for common terms. A 101M model gets these wrong
    often enough that answering from a checked glossary - clearly labelled -
    is more useful than generating them."""
    lowered = question.lower()
    for keys, text in FINANCIAL_KNOWLEDGE_BASE.items():
        if any(k in lowered for k in keys):
            return f"{text}\\n\\n_Source: curated glossary (not model-generated)._"
    return None


def answer(question, max_new_tokens, temperature):
    question = (question or "").strip()
    if not question:
        return "Ask a financial question."
    decision = classify(question)

    # Try the calculator whenever the question carries figures - the router
    # labels several multi-step questions as knowledge/reasoning, and a
    # question with numbers in it should never be answered by a 101M model.
    if decision.route == Route.NUMERICAL or any(c.isdigit() for c in question):
        computed = try_calculator(question)
        if computed:
            return computed

    if decision.route == Route.FINANCIAL_KNOWLEDGE:
        known = try_glossary(question)
        if known:
            return known

    text = generate(f"Question: {question}\\nAnswer:", int(max_new_tokens), float(temperature))
    report = analyze_output(text)
    if report.is_degenerate:
        # Say so rather than presenting noise as an answer.
        return ("_The model's output for this prompt was withheld: "
                f"{'; '.join(report.reasons)}._" + DISCLAIMER)
    return text + DISCLAIMER


demo = gr.Interface(
    fn=answer,
    inputs=[
        gr.Textbox(label="Question", placeholder="What is EBITDA?", lines=2),
        gr.Slider(16, 160, value=64, step=8, label="Max new tokens"),
        gr.Slider(0.1, 1.2, value=0.7, step=0.1, label="Temperature"),
    ],
    outputs=gr.Markdown(label="Answer"),
    title="Aivora Financial LLM (101M, trained from scratch)",
    description=(
        "A DeepSeek-V3-style model (Mixture-of-Experts, multi-head latent attention, "
        "multi-token prediction) trained from scratch on ~1.9B tokens. "
        "**Numbers are computed by a deterministic calculator, not by the model.** "
        "The model's prose is fluent but frequently factually wrong - see the model card."
    ),
    examples=[
        ["What is EBITDA?", 64, 0.7],
        ["Revenue is 500 and EBITDA is 100. Calculate EBITDA margin.", 64, 0.7],
        ["What is the current ratio if current assets are 300 and current liabilities are 150?", 64, 0.7],
        ["What is working capital?", 64, 0.7],
    ],
)

if __name__ == "__main__":
    demo.launch()
'''

REQUIREMENTS = """torch>=2.2
tiktoken>=0.5
safetensors>=0.4
gradio>=4.0
"""


def model_card(meta, param_count):
    cfg = meta["model_config"]
    return f"""---
license: other
language:
- en
tags:
- finance
- deepseek
- mixture-of-experts
- from-scratch
pipeline_tag: text-generation
---

# Aivora Financial LLM ({param_count / 1e6:.0f}M, trained from scratch)

A DeepSeek-V3-style language model built and trained from scratch for finance:
Mixture-of-Experts feed-forward layers, multi-head latent attention (MLA) with
compressed KV, and multi-token prediction (MTP).

This is a **learning/research artifact, not a production assistant.** It writes
fluent finance-flavoured text, and its facts are often wrong.

## What it actually scores

| metric | value |
| --- | --- |
| validation loss | **{meta['val_loss']:.4f}** (random guessing at this vocabulary is 10.82) |
| training steps | {meta['step']:,} |
| tokens seen | {meta['tokens_processed']:,} |
| 45-question finance quiz, model generating alone | **1-5 / 45** |
| 45-question finance quiz, **full demo pipeline** | **35 / 45 (77.8%)** |

The pipeline number is what this Space actually scores: exact arithmetic from
the calculator (including multi-step identities - ROE from assets and
liabilities, P/E from net income and share count, margins from components),
checked definitions from a curated glossary, and model generation only when it
passes a degeneracy guard. Every answer is labelled with its source.

For comparison, on the same 45 questions, Qwen2.5-1.5B-Instruct scores 38/45
without any training on this data. A 101M model trained on 1.9B tokens cannot
compete with models pretrained on trillions - that is the honest conclusion of
this project, not a bug.

## Architecture

| | |
| --- | --- |
| parameters | {param_count:,} |
| layers | {cfg['n_layer']} |
| embedding dim | {cfg['n_embd']} |
| attention heads | {cfg['n_head']} |
| experts / active per token | {cfg['n_experts']} / {cfg['n_experts_per_token']} |
| KV LoRA rank (MLA) | {cfg['kv_lora_rank']} |
| context length | {cfg['block_size']} |
| tokenizer | GPT-2 BPE ({cfg['vocab_size']} tokens) |

## Training

Trained on a free Kaggle T4 x2 across several sessions, on a mix of general
and financial text (FineWeb-Edu, Investopedia, SEC/EDGAR filings, finance Q&A
and instruction sets). Continuation runs used peak LR 3e-5, cosine decay to
1e-5, 500-step warmup after each resume, gradient clipping 1.0 and fp16 loss
scaling.

## Numbers are not generated

The bundled demo routes any question containing figures to a deterministic
calculator (EBITDA margin, current ratio, ROE, P/E and others). A model this
size cannot be trusted with arithmetic, so it is not asked to do it.

## Usage

```python
import json, torch, tiktoken
from safetensors.torch import load_file
from models import DeepSeekConfig, DeepSeekV3

meta = json.load(open("config.json"))
model = DeepSeekV3(DeepSeekConfig.from_dict(meta["model_config"]))
model.load_state_dict({{k: v.float() for k, v in load_file("model.safetensors").items()}})
model.eval()

enc = tiktoken.get_encoding("gpt2")
ids = torch.tensor(enc.encode_ordinary("Question: What is EBITDA?\\nAnswer:")).unsqueeze(0)
print(enc.decode(model.generate(ids, 64, temperature=0.7, top_k=40)[0].tolist()))
```

## Limitations

- Facts are frequently wrong; do not use for decisions.
- No instruction tuning in these weights (tuning it overfitted at two learning rates).
- English only, 1024-token context.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoint", required=True)
    ap.add_argument("--out", default="hf_export")
    args = ap.parse_args()

    import torch
    from safetensors.torch import save_file

    meta_path = args.checkpoint.rsplit(".pt", 1)[0] + ".json"
    with open(meta_path) as f:
        meta = json.load(f)

    out = args.out
    os.makedirs(out, exist_ok=True)

    print(f"Loading {args.checkpoint} ...")
    ckpt = torch.load(args.checkpoint, map_location="cpu")
    state = ckpt["model_state_dict"]
    # fp16 halves the download; contiguous() because safetensors rejects
    # tensors that share storage (this model ties some weights).
    half = {k: v.detach().half().contiguous().clone() for k, v in state.items()}
    params = sum(v.numel() for v in half.values())
    save_file(half, os.path.join(out, "model.safetensors"))
    del ckpt, state, half

    keep = {k: meta[k] for k in ("step", "train_loss", "val_loss", "best_val_loss",
                                 "tokens_processed", "model_config", "dataset_config",
                                 "seed", "timestamp") if k in meta}
    with open(os.path.join(out, "config.json"), "w") as f:
        json.dump(keep, f, indent=2)

    shutil.copytree(os.path.join(ROOT, "models"), os.path.join(out, "models"),
                    dirs_exist_ok=True,
                    ignore=shutil.ignore_patterns("__pycache__"))
    shutil.copy2(os.path.join(ROOT, "tools", "financial_calculator.py"), out)
    shutil.copy2(os.path.join(ROOT, "tools", "derived_calculations.py"), out)
    services = os.path.join(ROOT, "app", "backend", "services")
    shutil.copy2(os.path.join(services, "financial_router.py"), out)
    shutil.copy2(os.path.join(services, "quality.py"), out)

    # The glossary lives inside chat_service.py, which pulls in the whole app.
    # Lift just that one assignment out by parsing the source, so the Space
    # needs no app dependencies and the text cannot drift from the app's.
    import ast

    with open(os.path.join(services, "chat_service.py"), encoding="utf-8") as f:
        chat_src = f.read()
    glossary_src = None
    for node in ast.parse(chat_src).body:
        if (isinstance(node, ast.Assign) and getattr(node.targets[0], "id", "")
                == "FINANCIAL_KNOWLEDGE_BASE"):
            glossary_src = ast.get_source_segment(chat_src, node)
    if glossary_src is None:
        raise SystemExit("FINANCIAL_KNOWLEDGE_BASE not found in chat_service.py")
    with open(os.path.join(out, "glossary.py"), "w", encoding="utf-8") as f:
        f.write('"""Curated finance definitions, copied verbatim from the app\'s\n'
                'chat_service.FINANCIAL_KNOWLEDGE_BASE by scripts/export_for_huggingface.py."""\n\n')
        f.write(glossary_src + "\n")

    # The demo is generated as text, so a bad escape in APP_PY ships a Space
    # that crashes on boot. Parse it before writing it out.
    import ast

    try:
        ast.parse(APP_PY)
    except SyntaxError as e:
        raise SystemExit(f"generated app.py is not valid Python: {e.msg} (line {e.lineno})")
    with open(os.path.join(out, "app.py"), "w", encoding="utf-8") as f:
        f.write(APP_PY)
    with open(os.path.join(out, "requirements.txt"), "w", encoding="utf-8") as f:
        f.write(REQUIREMENTS)
    with open(os.path.join(out, "README.md"), "w", encoding="utf-8") as f:
        f.write(model_card(meta, params))

    # Running the bundle locally leaves __pycache__ behind; don't ship it.
    for dirpath, dirnames, _ in list(os.walk(out)):
        for d in list(dirnames):
            if d == "__pycache__":
                shutil.rmtree(os.path.join(dirpath, d), ignore_errors=True)
                dirnames.remove(d)

    total = sum(os.path.getsize(os.path.join(dp, f))
                for dp, _, fs in os.walk(out) for f in fs)
    print(f"\nWrote {out}/ ({total / 1e6:.0f} MB)")
    for dp, _, fs in os.walk(out):
        for f in sorted(fs):
            p = os.path.join(dp, f)
            print(f"  {os.path.relpath(p, out):44} {os.path.getsize(p) / 1e6:7.1f} MB")


if __name__ == "__main__":
    main()
